### ISSUE TITLE
Missing way to serialize and deserialize GameObjects and Scene

### ISSUE THREAD

**Issue by FreshMag** [FreshMag/AgentSeek#16]
Maybe yaml format with custom extension files (".gameObject", ".scene") (?)

**Comment by FreshMag** [comment]
@ThomasCapelli I think the following aspects of a GameObject should be serialized:
- Rigidbody
- List of components' classes in the form of their fully qualified names (e.g. `io.github.agentseek.util.DummyComponent`)
- For each component, in case its constructor accepts some arguments (apart from the GameObject), also the fully qualified name for each argument and the passed value should be indicated

For example, for `HealthIntComponent`, it should be something like this:
```yaml
rigidbody:
   type: io.github.agentseek.physics.RigidBody.CircleRigidBody
   shape: 
      name: io.github.agentseek.common.Circle2d
      parameters:
         - name: radius
           class: kotlin.Double
           value: 10.0
       ...
components:
   - class: io.github.agentseek.components.HealthIntComponent
     arguments:
        - name: maxHp
          type: kotlin.Int
          value: 5

...

```
